QueueAge workaround for java.lang.NoClassDefFoundError
If broker has missing JARs and exception java.lang.NoClassDefFoundError is thrown, instead of using REST/API Jolokia, retrieve message timestamps from browse.jsp